name: unit_converter
description: A Unit Converter app.

dependencies:

  flutter:
    sdk: flutter
    
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/data/regular_units.json
    - assets/icons/area.png
    - assets/icons/currency.png
    - assets/icons/digital_storage.png
    - assets/icons/length.png
    - assets/icons/mass.png
    - assets/icons/power.png
    - assets/icons/time.png
    - assets/icons/volume.png

  fonts:
    - family: Raleway
      fonts:
        - asset: third_party/Raleway-Regular.ttf